dev/SwinSchool/SwinSchool/SwinSchool.WebUI/Controllers/AdminController.cs
using SwinSchool.CommonShared.Dto;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ServiceModel;
using SwinSchool.WebUI.Service;
using SwinSchool.WebUI.Models;
using System.ServiceModel.MsmqIntegration;
using System.Transactions;

namespace SwinSchool.WebUI.Controllers
{
    [Authorize(Roles ="Administrator")]
    public class AdminController : Controller
    {
        MyUserBOClient _myUserService = ServiceFactory.CreateUserBoClient();

        //
        // GET: /User/

        public ActionResult Index()
        {
            List<MyUserDto> allUserList = new List<MyUserDto>();
            allUserList = new List<MyUserDto>(_myUserService.GetAllUsers());

            return View(allUserList);
        }
        
        //
        // GET: /User/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /User/Create

        [HttpPost]
        public ActionResult Create(MyUserDto myUser)
        {
            try
            {
                _myUserService.CreateUser(myUser);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /User/Edit/5

        public ActionResult Edit(string id)
        {
            return View(_myUserService.GetUserById(id));
        }

        //
        // POST: /User/Edit/5

        [HttpPost]
        public ActionResult Edit(MyUserDto myUser, FormCollection collection)
        {
            try
            {
                if(collection["hfAction"]=="Save")
                {
                    _myUserService.UpdateUser(myUser);
                }   
                else if (collection["hfAction"] == "Delete")
                {
                    _myUserService.DeleteUser(myUser.UserID);
                }
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                return View(myUser);
            }
        }

        //
        // POST: /User/Delete/5

        [HttpPost]
        public ActionResult Delete(string id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public ActionResult ResetPassword(string id)
        {
            var user = _myUserService.GetUserById(id);

            ResetPasswordRequestViewModel vm = new ResetPasswordRequestViewModel()
            {
                Name = user.Name,
                UserID = user.UserID
            };
            
            return View(vm);
        }

        public ActionResult ResetPasswordSuccess()
        {
            return View();
        }
    }
}

dev/SwinSchool/SwinSchool/SwinSchool.WebUI/Controllers/EmployeeController.cs
using SwinSchool.WebUI.Models;
using SwinSchool.WebUI.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SwinSchool.WebUI.Controllers
{
    [Authorize(Roles = "Administrator,Employee")]
    public class EmployeeController : Controller
    {
        MyUserBOClient _myUserService = ServiceFactory.CreateUserBoClient();
        //
        // GET: /User/

        public ActionResult Index()
        {
            var userDetail = (User as SwinSchool.WebUI.Security.UserPrincipal).SerializedData;
            return View(userDetail);
        }

        [Authorize(Roles = "Administrator,Employee")]
        public ActionResult ResetPassword(string id)
        {
            var user = _myUserService.GetUserById(id);

            ResetPasswordRequestViewModel vm = new ResetPasswordRequestViewModel()
            {
                Name = user.Name,
                UserID = user.UserID
            };

            return View(vm);
        }

        public ActionResult ResetPasswordSuccess()
        {
            return View();
        }
    }
}

dev/SwinSchool/SwinSchool/SwinSchool.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/angular/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Latest compiled and minified CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Optional theme -->
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="@Url.Action("Index","Home")">
                    SECURE
                </a>
            </div>

            <ul class="nav navbar-nav">
                @{
                    if (User != null && User.IsInRole("Administrator"))
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User administrator <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Index","Admin")">User listing</a></li>
                                <li><a href="@Url.Action("Create","Admin")">Create user</a></li>
                            </ul>
                        </li>
                    }
                    if (User != null && User.IsInRole("Employee|Administrator"))
                    {
                        <li><a href="@Url.Action("Index","Employee")">User profile</a></li>
                    }
                    if (User == null)
                    {
                        <li><a href="@Url.Action("Login","Account")">Login</a></li>
                    }
                }

                
            </ul>

            @{ 
                if (User != null && User is SwinSchool.WebUI.Security.UserPrincipal)
                {
                    <p class="navbar-text">
                        Your are in role: @(Roles.GetRolesForUser().FirstOrDefault())
                    </p>
                }
            }

            @{
                if (User != null && User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="@Url.Action("Logout", "Account")">Logout</a></li>
                    </ul>
                }
            }
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    <!-- Latest compiled and minified JavaScript -->

    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>